name: Tensionr Data Synchronizer

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download xx_ent_wiki_sm

    - name: Fetch data from GDELT
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        TENSIONR_SIGNATURE_KEY: ${{ secrets.TENSIONR_SIGNATURE_KEY }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python src/fetch_gdelt.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automated update of GDELT data"
        file_pattern: 'data/latest.json'
